name: recordinvest
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.5.2+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: any
  dropdown_search: ^5.0.2
  intl: ^0.17.0
  syncfusion_flutter_charts: ^20.3.47
  shared_preferences: ^2.0.15
  get: ^4.6.5
  flutter_screenutil: ^5.9.1
  lottie: ^2.3.2
  google_fonts: ^4.0.5
  webview_flutter: ^3.0.4
  persistent_bottom_nav_bar: ^5.0.2
  camera: ^0.10.5+2
  onesignal_flutter: ^3.5.1
  hive: ^2.2.3
  chewie: ^1.3.2
  video_player: ^2.7.0
  path_provider: ^2.0.15
  permission_handler: ^10.4.1
  flutter_background_service: ^5.0.5
  device_info_plus: ^9.1.2
  package_info_plus: ^4.2.0
  flutter_background_service_android: ^6.2.2
  flutter_local_notifications: ^16.3.2
  collection: ^1.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
